server:
  port: '8082'

spring:
  profiles:
    active: dev
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mydb
    password: Element01!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    activate:
      on-profile: dev
welcome:
  message: Hello from the dev custom configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mydb
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    activate:
      on-profile: qa
welcome:
  message: Hello from the qa custom configuration
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mydb
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    activate:
      on-profile: prod
welcome:
  message: Hello from the prod custom configuration
